blueprint:
  name: My Motion-activated Light
  description: Turn on a light when motion is detected, and off when no longer detected (if not already on).
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor (or Group)
      selector:
        entity:
          domain: binary_sensor
          # device_class: motion
    luminance_sensor:
      name: Ambient sensor
      description: "Sensor to determine ambient light threshold"
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    luminance_threshold:
      name: Luminance threshold
      description: "Only turn on the light if luminance is above this value."
      default: 40
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: lux
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

variables:
  lights: !input light_target

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

# condition:
#   - alias: "If not already on"
#     condition: template
#     value_template: "{{ expand(lights.entity_id) | selectattr('state', '==', 'on') | list | count == 0 }}"

action:
  - if:
    - condition: template
      alias: "If not already on"
      value_template: "{{ expand(lights.entity_id) | selectattr('state', '==', 'on') | list | count == 0 }}"
    - condition: numeric_state
      alias: "If below luminence threshold"
      entity_id: !input luminance_sensor
      below: !input luminance_threshold
    then:
    - alias: "Turn on the light"
      service: light.turn_on
      target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      to: "off"
      for: "00:01:00"
    timeout: "00:05:00"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
